/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './azure-mobile-app-services-client.module';
import * as i2 from './azure-mobile-app-services-client.service';
export const AzureMobileAppServicesClientModuleNgFactory:i0.NgModuleFactory<i1.AzureMobileAppServicesClientModule> = i0.ɵcmf(i1.AzureMobileAppServicesClientModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,([] as any[])],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,
          i2.AzureMobileAppServicesClientService,i2.AzureMobileAppServicesClientService,
          ([] as any[])),i0.ɵmpd(512,i1.AzureMobileAppServicesClientModule,i1.AzureMobileAppServicesClientModule,
          ([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovX3NyYy9hbmd1bGFyLWF6dXJlLW1vYmlsZS1hcHAtc2VydmljZS1jbGllbnQvc3JjL2F6dXJlLW1vYmlsZS1hcHAtc2VydmljZXMtY2xpZW50Lm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9fc3JjL2FuZ3VsYXItYXp1cmUtbW9iaWxlLWFwcC1zZXJ2aWNlLWNsaWVudC9zcmMvYXp1cmUtbW9iaWxlLWFwcC1zZXJ2aWNlcy1jbGllbnQubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
